"""Public surface for the embedded AstralPlane durable-state boundary."""

from astralplane.api import (
    PlaneHealth,
    PlaneRuntime,
    RepositoryCatalog,
    create_artifact_repository,
    create_audit_repository,
    create_audit_retention_repository,
    create_encrypted_llm_config_repository,
    create_history_repository,
    create_outbox_store,
    create_plane_runtime,
    create_preferences_repository,
    create_purge_store,
    create_remote_repository,
    create_repository_catalog,
    create_revocation_repository,
    create_scheduler_repository,
    create_voice_repository,
    create_workspace_repository,
)
from astralplane.compatibility import (
    BLOB_LAYOUT_VERSION,
    CONTRACT_VERSION,
    MINIMUM_CONSUMER_VERSION,
    PACKAGE_VERSION,
    RECOVERY_CONTRACT_VERSION,
    CompatibilityReport,
    CompatibilityState,
    inspect_compatibility,
)
from astralplane.database.bootstrap import (
    BootInitializer,
    BootReconciliationRunner,
    BootStatus,
    InitializationReport,
)
from astralplane.database.migrations import (
    CURRENT_DATA_PLANE_REVISION,
    MIGRATION_DIGEST,
    MIGRATION_REGISTRY,
    Migration,
    MigrationRegistry,
    MigrationReport,
    MigrationRunner,
)
from astralplane.database.pool import ConnectionPool
from astralplane.database.revision import (
    ADVISORY_LOCK_IDS,
    READ_COMPATIBLE_FROM,
    SCHEMA_REVISION,
    DataPlaneRevision,
)
from astralplane.database.transaction import CommandResult, PlaneDatabase, Transaction
from astralplane.reconciliation import (
    RECONCILIATION_ADVISORY_LOCK,
    ReconciliationHookReport,
    ReconciliationPlan,
    ReconciliationReport,
    ReconciliationRunner,
)
from astralplane.reconciliation_store import (
    PostgresReconciliationCoordinator,
    PostgresReconciliationSession,
)

__version__ = PACKAGE_VERSION

__all__ = (
    "ADVISORY_LOCK_IDS",
    "BLOB_LAYOUT_VERSION",
    "CONTRACT_VERSION",
    "CURRENT_DATA_PLANE_REVISION",
    "MIGRATION_DIGEST",
    "MIGRATION_REGISTRY",
    "MINIMUM_CONSUMER_VERSION",
    "PACKAGE_VERSION",
    "READ_COMPATIBLE_FROM",
    "RECONCILIATION_ADVISORY_LOCK",
    "RECOVERY_CONTRACT_VERSION",
    "SCHEMA_REVISION",
    "BootInitializer",
    "BootReconciliationRunner",
    "BootStatus",
    "CommandResult",
    "CompatibilityReport",
    "CompatibilityState",
    "ConnectionPool",
    "DataPlaneRevision",
    "InitializationReport",
    "Migration",
    "MigrationRegistry",
    "MigrationReport",
    "MigrationRunner",
    "PlaneDatabase",
    "PlaneHealth",
    "PlaneRuntime",
    "PostgresReconciliationCoordinator",
    "PostgresReconciliationSession",
    "ReconciliationHookReport",
    "ReconciliationPlan",
    "ReconciliationReport",
    "ReconciliationRunner",
    "RepositoryCatalog",
    "Transaction",
    "__version__",
    "create_artifact_repository",
    "create_audit_repository",
    "create_audit_retention_repository",
    "create_encrypted_llm_config_repository",
    "create_history_repository",
    "create_outbox_store",
    "create_plane_runtime",
    "create_preferences_repository",
    "create_purge_store",
    "create_remote_repository",
    "create_repository_catalog",
    "create_revocation_repository",
    "create_scheduler_repository",
    "create_voice_repository",
    "create_workspace_repository",
    "inspect_compatibility",
)
